<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '027c4458d0e8a1415b7e163703b9f5ca',
  'DATABASE_URL' => 'mysql://root@localhost:3308/sw_artefact_test?serverVersion=8.0.18',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
